---
configure_dock_items: no
configure_dotfiles: no
configure_repositories: no
configure_sudoers: no
configure_prefs: no
configure_osx: no
configure_mas: no
configure_homebrew: no
configure_npm: no
configure_visual_studio_code_extensions: no

homebrew_upgrade_all_packages: no

homebrew_installed_packages:
  - ansible
  - dockutil
  - git
  - node
  - openssl
  - python

dock_items_to_remove:
  - App Store
  - Calendar
  - Contacts
  - FaceTime
  - iTunes
  - iBooks
  - Keynote
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Notes
  - Numbers
  - Pages
  - Photos
  - Reminders
  - Safari
  - Siri
  - System Preferences

dock_items_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 2
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app"
    pos: 3
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 4
  - name: SourceTree
    path: "/Applications/SourceTree.app"
    pos: 5
  - name: Terminal
    path: "/Applications/Utilities/Terminal.app"
    pos: 6

dotfiles_files:
  - .aliases
  - .bash_profile
  - .bash_prompt
  - .bashrc
  - .curlrc
  - .editorconfig
  - .functions
  - .gitattributes
  - .gitconfig
  - .gitignore
  - .gitignore_global
  - .hushlogin
  - .inputrc
  - .osx
  - .screenrc
  - .wgetrc

mas_installed_apps:
  - { id: 497799835, name: "Xcode" }

npm_absent_globals: []

npm_latest_globals:
  - '@angular/cli'

repository_configs:
  - { repo: 'git://github.com/donaldaverill/mac-dev-playbook.git',
      dest: '~/src/ansible/MacPlaybook' }
  - { repo: 'git://github.com/donaldaverill/dotfiles.git',
      dest: '~/src/dotfiles' }
