---
configure_dock_items: yes
configure_dotfiles: yes
configure_repositories: yes
configure_sudoers: yes
configure_prefs: yes
configure_osx: yes
configure_mas: yes
configure_meteor: yes
configure_homebrew: yes
configure_npm: yes
configure_visual_studio_code_extensions: yes

homebrew_installed_packages:
  - ansible
  - docker
  - dockutil
  - git
  - gpg
  - graphicsmagick
  - mongodb
  - node
  - openssl
  - python

homebrew_cask_apps:
  - firefox
  - google-chrome
  - google-chrome-canary
  - microsoft-office
  - ngrok
  - slack
  - sourcetree
  - visual-studio-code

dock_items_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Calendar

dock_items_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app"
    pos: 2
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 3
  - name: Source Tree
    path: "/Applications/SourceTree.app"
    pos: 4

dotfiles_files:
  - .aliases
  - .bash_profile
  - .bash_prompt
  - .bashrc
  - .curlrc
  - .editorconfig
  - .functions
  - .gitattributes
  - .gitconfig
  - .gitignore
  - .gitignore_global
  - .hushlogin
  - .inputrc
  - .osx
  - .screenrc
  - .wgetrc

mas_installed_apps:
  - { id: 497799835, name: "Xcode" }

npm_absent_globals: []

npm_latest_globals:
  - '@angular/cli'

repository_configs:
  - { repo: 'git://github.com/donaldaverill/mac-dev-playbook.git',
      dest: '~/src/ansible/MacPlaybook' }
  - { repo: 'https://github.com/donaldaverill/dotfiles',
      dest: '~/src/dotfiles' }

visual_studio_code_extensions:
  - alefragnani.bookmarks
  - Angular.ng-template
  - CoenraadS.bracket-pair-colorizer
  - christian-kohler.npm-intellisense
  - dbaeumer.vscode-eslint
  - donjayamanne.githistory
  - eamodio.gitlens
  - EditorConfig.EditorConfig
  - eg2.tslint
  - eg2.vscode-npm-script
  - haaaad.ansible
  - IBM.output-colorizer
  - ms-vscode.typescript-javascript-grammar
  - msjsdiag.debugger-for-chrome
  - natewallace.angular2-inline
  - pflannery.vscode-versionlens
  - robertohuertasm.vscode-icons
  - WallabyJs.wallaby-vscode
