---
downloads: ~/.ansible-downloads/

configure_dock_items: no
configure_dotfiles: no
configure_homebrew: no
configure_sudoers: no
configure_npm: no
configure_prefs: no
configure_osx: no
configure_repositories: no
configure_visual_studio_code_extensions: no
configure_mas: no
configure_meteor: no

home: "{{ lookup('env','HOME') }}"

homebrew_upgrade_all_packages: no

homebrew_installed_packages: []

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications

homebrew_cask_apps: []

dock_items_to_remove: []

dock_items_to_persist: []

dotfiles_repo: https://github.com/donaldaverill/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/src/dotfiles
dotfiles_home: "~"
dotfiles_files: []

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids:
  - 497799835 # Xcode

meteor_version: "1.6"

npm_absent_globals: []

npm_latest_globals: []

repository_configs: []

visual_studio_code_extensions: []
