---
downloads: ~/.ansible-downloads/

configure_dock_items: no
configure_dotfiles: no
configure_homebrew: no
configure_sudoers: no
configure_npm: no
configure_prefs: no
configure_osx: no
configure_repositories: no
configure_visual_studio_code_extensions: no
configure_mas: no
configure_meteor: no

home: "{{ lookup('env','HOME') }}"

homebrew_upgrade_all_packages: no

homebrew_installed_packages:
  - ansible
  - docker
  - dockutil
  - git
  - gpg
  - graphicsmagick
  - mongodb
  - node
  - openssl
  - python
  - tree
  - wget

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - arduino
  - firefox
  - google-chrome
  - google-chrome-canary
  - microsoft-office
  - ngrok
  - slack
  - sourcetree
  - visual-studio-code

dock_items_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Calendar

dock_items_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app"
    pos: 2
  - name: Source Tree
    path: "/Applications/SourceTree.app"
    pos: 3
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 4

dotfiles_repo: https://github.com/donaldaverill/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/src/dotfiles
dotfiles_home: "~"
dotfiles_files:
  - .aliases
  - .bash_profile
  - .bash_prompt
  - .bashrc
  - .curlrc
  - .editorconfig
  - .functions
  - .gitattributes
  - .gitconfig
  - .gitignore
  - .gitignore_global
  - .hushlogin
  - .inputrc
  - .osx
  - .screenrc
  - .wgetrc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids:
  - 497799835 # Xcode

meteor_version: "1.6"

npm_absent_globals: []

npm_latest_globals: []

repository_configs: []

visual_studio_code_extensions:
  - EditorConfig.EditorConfig
  - haaaad.ansible

