---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_prefs: yes
configure_osx: yes

home: "{{ lookup('env','HOME') }}"

homebrew_upgrade_all_packages: no

homebrew_installed_packages:
  - ansible
  - docker
  - dockutil
  - git
  - graphicsmagick
  - openssl
  - python
  - tree
  - wget

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - android-file-transfer
  - arduino
  - docker
  - dropbox
  - overdrive-media-console
  - etcher
  - firefox
  - gitkraken
  - google-chrome
  - google-chrome-canary
  - microsoft-office
  - sdformatter
  - slack
  - vagrant
  - virtualbox
  - visual-studio
  - visual-studio-code

dock_items_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Calendar

dock_items_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app"
    pos: 2
  - name: GitKraken
    path: "/Applications/GitKraken.app"
    pos: 3
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 4

dotfiles_repo: https://github.com/donaldaverill/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/src/dotfiles
dotfiles_home: "~"
dotfiles_files:
  - .aliases
  - .bash_profile
  - .bash_prompt
  - .bashrc
  - .curlrc
  - .editorconfig
  - .functions
  - .gitattributes
  - .gitconfig
  - .gitignore
  - .gitignore_global
  - .hushlogin
  - .inputrc
  - .osx
  - .screenrc
  - .wgetrc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids:
  - 411643860 # DaisyDisk
  - 497799835 # Xcode

visual_studio_code_extensions:
  - eg2.tslint
  - timonwong.ansible-autocomplete
  - PeterJausovec.vscode-docker
  - EditorConfig.EditorConfig
  - dbaeumer.vscode-eslint
  - haaaad.ansible
  - donjayamanne.python
  - marcostazi.VS-code-vagrantfile
  - robertohuertasm.vscode-icons
  - djabraham.vscode-yaml-validation
  - sbrink.elm
  - ms-vscode.Theme-MarkdownKit
  - DavidAnson.vscode-markdownlint
  - donjayamanne.githistory
  - Zignd.html-css-class-completion
  - xabikos.JavaScriptSnippets
  - abusaidm.html-snippets
  - magicstack.MagicPython
  - msjsdiag.debugger-for-chrome
  - lukehoban.Go
  - formulahendry.code-runner
  - Ionide.Ionide-fsharp
  - eg2.vscode-npm-script
  - shinnn.stylelint
  - joelday.docthis
  - stevencl.addDocComments
  - christian-kohler.path-intellisense
  - christian-kohler.npm-intellisense
  - alefragnani.Bookmarks
  - anseki.vscode-color
  - dzannotti.vscode-babel-coloring
  - DSKWRK.vscode-generate-getter-setter
  - streetsidesoftware.code-spell-checker
  - spywhere.guides
  - codezombiech.gitignore
  - naumovs.color-highlight
  - dkundel.vscode-npm-source
  - steoates.autoimport
  - abadi199.elm-format
  - rbbit.typescript-hero
  - Rubymaniac.vscode-html-to-elm

