---
downloads: ~/.ansible-downloads/

configure_dock_items: no
configure_dotfiles: no
configure_homebrew: no
configure_sudoers: no
configure_npm: no
configure_prefs: no
configure_osx: no
configure_repositories: no
configure_visual_studio_code_extensions: no
configure_mas: no
configure_meteor: no

home: "{{ lookup('env','HOME') }}"

homebrew_upgrade_all_packages: no

homebrew_installed_packages:
  - ansible
  - docker
  - dockutil
  - git
  - gpg
  - graphicsmagick
  - mongodb
  - node
  - openssl
  - python
  - tree
  - wget
  - yarn

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - android-file-transfer
  - arduino
  - docker
  - dropbox
  - overdrive-media-console
  - etcher
  - firefox
  - google-chrome
  - google-chrome-canary
  - google-drive
  - iterm2
  - microsoft-office
  - mongotron
  - ngrok
  - screenhero
  - sdformatter
  - slack
  - sourcetree
  - vagrant
  - virtualbox
  - visual-studio
  - visual-studio-code

dock_items_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Calendar

dock_items_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app"
    pos: 2
  - name: Source Tree
    path: "/Applications/SourceTree.app"
    pos: 3
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 4

dotfiles_repo: https://github.com/donaldaverill/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/src/dotfiles
dotfiles_home: "~"
dotfiles_files:
  - .aliases
  - .bash_profile
  - .bash_prompt
  - .bashrc
  - .curlrc
  - .editorconfig
  - .functions
  - .gitattributes
  - .gitconfig
  - .gitignore
  - .gitignore_global
  - .hushlogin
  - .inputrc
  - .osx
  - .screenrc
  - .wgetrc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids:
  - 411643860 # DaisyDisk
  - 497799835 # Xcode

meteor_version: "1.4.2.6"

npm_absent_globals: []

npm_latest_globals: []

repository_configs:
  - { repo: 'git://github.com/donaldaverill/meteor-app-example-arduino-serialport.git',
    dest: '~/src/meteor/app-example-arduino-serialport' }

visual_studio_code_extensions:
  - alefragnani.Bookmarks
  - christian-kohler.path-intellisense
  - christian-kohler.npm-intellisense
  - dbaeumer.vscode-eslint
  - donjayamanne.githistory
  - EditorConfig.EditorConfig
  - eg2.tslint
  - eg2.vscode-npm-script
  - haaaad.ansible
  - HookyQR.beautify
  - naumovs.color-highlight
  - PeterJausovec.vscode-docker
  - robertohuertasm.vscode-icons
  - steoates.autoimport
  - timonwong.ansible-autocomplete
  # - donjayamanne.python
  # - marcostazi.VS-code-vagrantfile
  # - djabraham.vscode-yaml-validation
  # - sbrink.elm
  # - ms-vscode.Theme-MarkdownKit
  # - DavidAnson.vscode-markdownlint
  # - Zignd.html-css-class-completion
  # - xabikos.JavaScriptSnippets
  # - abusaidm.html-snippets
  # - magicstack.MagicPython
  # - msjsdiag.debugger-for-chrome
  # - lukehoban.Go
  # - formulahendry.code-runner
  # - Ionide.Ionide-fsharp
  # - shinnn.stylelint
  # - joelday.docthis
  # - stevencl.addDocComments
  # - anseki.vscode-color
  # - dzannotti.vscode-babel-coloring
  # - DSKWRK.vscode-generate-getter-setter
  # - streetsidesoftware.code-spell-checker
  # - spywhere.guides
  # - codezombiech.gitignore
  # - dkundel.vscode-npm-source
  # - abadi199.elm-format
  # - rbbit.typescript-hero
  # - Rubymaniac.vscode-html-to-elm

