---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
    - role: geerlingguy.homebrew
      when: configure_homebrew
    # - role: visual-studio-code-extensions
    #   users:
    #     - username: "{{ansible_user_id}}"
    #       visual_studio_code_extensions: "{{ visual_studio_code_extensions }}"
    #   when: configure_visual_studio_code_extensions
    - role: geerlingguy.mas
      when:
        - mas_installed_app_ids
        - configure_mas

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/preferences.yml
      when: configure_prefs

    - include: tasks/sudoers.yml
      when: configure_sudoers

    - include: tasks/osx.yml
      when: configure_osx

    - include: tasks/repositories.yml
      when: configure_repositories

    - include: tasks/npm.yml
      when: configure_npm

    - include: tasks/meteor.yml
      when: configure_meteor

    - name: Remove all unwanted items from dock
      shell: dockutil --remove "{{ item }}"
      ignore_errors: true
      with_items: "{{ dock_items_to_remove }}"
      when: configure_dock_items

    - name: Check if items in dock exist
      shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
      with_items: "{{ dock_items_to_persist }}"
      when: configure_dock_items

    - name: Fix order
      shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
      with_items: "{{ dock_items_to_persist }}"
      when: configure_dock_items

